--1
SELECT F.NAME, F.PATH, F.SIZE
FROM PRIVILEGE P
INNER JOIN FILE F on P.ID_FILE = F.ID
INNER JOIN CLIENT C on C.ID = P.ID_CLIENT
WHERE C.ID = 1;

--2
SELECT TOO.NAME, C.NAME, C.PATRONYMIC, C.SURNAME
FROM HISTORY_OF_OPERATIONS HOP
INNER JOIN CLIENT C on C.ID = HOP.ID_CLIENT
INNER JOIN TYPE_OF_OPERATION TOO on TOO.ID = HOP.ID_TYPE_OF_OPERATION
WHERE HOP.ID_FILE = 2;

--3
