--1
SELECT F.ID, F.NAME, F.PATH, F.SIZE
FROM PRIVILEGE P
INNER JOIN FILE F on P.ID_FILE = F.ID
INNER JOIN CLIENT C on C.ID = P.ID_CLIENT
WHERE C.ID = 1;

--2
SELECT TOO.NAME, C.NAME, C.PATRONYMIC, C.SURNAME
FROM HISTORY_OF_OPERATION HOP
INNER JOIN CLIENT C on C.ID = HOP.ID_CLIENT
INNER JOIN TYPE_OF_OPERATION TOO on TOO.ID = HOP.ID_TYPE_OF_OPERATION
WHERE HOP.ID_FILE = 2;

--3
SELECT F.ID, F.NAME, F.PATH, F.SIZE, HOP.DATE_OF_OPERATION
FROM HISTORY_OF_OPERATION HOP
INNER JOIN FILE F on F.ID = HOP.ID_FILE
INNER JOIN TYPE_OF_OPERATION TOO on TOO.ID = HOP.ID_TYPE_OF_OPERATION
WHERE TOO.NAME = 'Скачать'
ORDER BY HOP.DATE_OF_OPERATION
    OFFSET 3;

--4
SELECT P.ID_FILE, F.NAME,COUNT(P.ID_FILE) AS count
FROM PRIVILEGE P
INNER JOIN FILE F on F.ID = P.ID_FILE
GROUP BY P.ID_FILE
ORDER BY count DESC
LIMIT 3;

--5
SELECT TOO.NAME, COUNT(TOO.NAME) AS count
FROM HISTORY_OF_OPERATION HOP
INNER JOIN TYPE_OF_OPERATION TOO on TOO.ID = HOP.ID_TYPE_OF_OPERATION
GROUP BY TOO.NAME
ORDER BY count DESC
LIMIT 2;

--6
SELECT COUNT(TOO.NAME)
FROM HISTORY_OF_OPERATION HOP
INNER JOIN TYPE_OF_OPERATION TOO on TOO.ID = HOP.ID_TYPE_OF_OPERATION
WHERE TOO.NAME = 'Скачать'
GROUP BY TOO.NAME;

SELECT C.NAME, C.PATRONYMIC, C.SURNAME
FROM HISTORY_OF_OPERATION HOP
INNER JOIN TYPE_OF_OPERATION TOO on TOO.ID = HOP.ID_TYPE_OF_OPERATION
INNER JOIN CLIENT C on C.ID = HOP.ID_CLIENT
WHERE TOO.NAME = 'Скачать';

--7
SELECT *
FROM FILE F
WHERE NAME LIKE '%.img';

SELECT *
FROM FILE F
WHERE PATH = 'home/Desktop';

SELECT *
FROM FILE F
WHERE SIZE = 5;

SELECT *
FROM FILE F
WHERE NAME LIKE '%.img' AND
      PATH = 'home/Telegram' AND
      SIZE = 82;

--8
SELECT ID_FILE,COUNT(ID_TAG), ROUND(1.0/COUNT(ID_TAG), 2) AS rating
FROM FILE_TAG
GROUP BY ID_FILE