create table PUBLIC.ADDRESS
(
    ID INTEGER auto_increment,
    COUNTRY CHARACTER VARYING(255),
    CITY CHARACTER VARYING(255),
    REGION CHARACTER VARYING(255),
    STREET CHARACTER VARYING(255),
    HOUSE CHARACTER VARYING(255),
    FLAT INTEGER,
    primary key (ID)
);

create table PUBLIC.DOCUMENT
(
    ID INTEGER auto_increment,
    ID_TYPE INTEGER,
    ID_PERSONAL_DATA INTEGER,
    START_DATE DATE,
    ENS_DATE DATE,
    primary key (ID)
);

create table PUBLIC.RELATIVE
(
    ID INTEGER auto_increment,
    NAME CHARACTER VARYING(255),
    PATRONYMIC CHARACTER VARYING(255),
    SURNAME CHARACTER VARYING(255),
    PHONE_NUMBER CHARACTER VARYING(255),
    primary key (ID)
);

create table PUBLIC.TYPE
(
    ID INTEGER auto_increment,
    NAME CHARACTER VARYING(255),
    primary key (ID)
);

create table PUBLIC.WORK_ACTIVITY
(
    ID INTEGER auto_increment,
    NAME_WORK CHARACTER VARYING(255),
    RATE INTEGER,
    SALARY CHARACTER VARYING(255),
    HOURS_WORKED INTEGER,
    DATE_OF_HIRING DATE,
    DATE_OF_DISMISSAL DATE,
    primary key (ID)
);

create table PUBLIC.PERSONAL_DATA
(
    ID INTEGER auto_increment,
    ID_ADDRESS INTEGER,
    ID_RELATIVE INTEGER,
    ID_WORK INTEGER,
    NAME CHARACTER VARYING(255),
    PATRONYMIC CHARACTER VARYING(255),
    SURNAME CHARACTER VARYING(255),
    PHONE_NUMBER CHARACTER VARYING(255),
    primary key (ID),
    foreign key (ID_ADDRESS) references PUBLIC.ADDRESS,
    foreign key (ID_RELATIVE) references PUBLIC.RELATIVE,
    foreign key (ID_WORK) references PUBLIC.WORK_ACTIVITY
);

